version: '3.1'

services:
  bd:
    image: mysql:8.0.25
    cap_add:
      - SYS_NICE
    container_name: mysql
    ports: 
        - 3306:3306
    environment:
      MYSQL_USER: vendas
      MYSQL_PASSWORD: vendas
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vendas_db
      
  jaeger:
      image: jaegertracing/all-in-one:1.22
      container_name: jaeger
      ports:   
          - 5775:5775/udp 
          - 6831:6831/udp 
          - 6832:6832/udp 
          - 5778:5778 
          - 16686:16686 
          - 14268:14268 
          - 14250:14250 
          - 9411:9411 
  prometheus:
      image: prom/prometheus:v2.27.1
      container_name: prometheus
      ports: 
        - 9090:9090
      volumes: 
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
      command: 
        - --config.file=/etc/prometheus/prometheus.yml

  grafana:
      image: grafana/grafana:8.0.1
      container_name: grafana
      ports:
        - 3000:3000